# Generated by Django 3.1.6 on 2021-02-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210205_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tea',
            old_name='caffeineLvl',
            new_name='strength',
        ),
    ]
