# Generated by Django 3.1.6 on 2021-02-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210206_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='variety',
            new_name='blend',
        ),
    ]
