# Generated by Django 3.1.6 on 2021-02-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210207_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tea',
            options={'ordering': ['id']},
        ),
    ]
