# Generated by Django 3.1.6 on 2021-02-08 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210208_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='servPerBag',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='servings',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
    ]
